import type { Metadata } from "next";
import { Barlow, Bellefair, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

// If loading a variable font, you don't need to specify the font weight

const barlow_condensed = Barlow_Condensed({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const bellefair = Bellefair({
  weight: ["400"],
  subsets: ["latin"],
});
const barlow = Barlow({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${bellefair.className} ${barlow_condensed.className} ${barlow.className} text-lb`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
